apiVersion: v1
kind: Service
metadata:
  name: mdim-authorization
  namespace: mdim-dev
spec:
  selector: 
    app: mdim-authorization
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
